server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:123456@tcp(0.0.0.0:3306)/touhou_gamejam?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_conn: 50
    max_open_conn: 100
    conn_max_lifetime: 30s
  redis:
    network: tcp
    addr: 0.0.0.0:6379
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
  objectStorage:
    domain: localhost:9000
    access_key_id: minioadmin
    secret_access_key: minioadmin
    location: cn-north-1
    secure: false
    token: ""

user:
  default_username_prefix: "thjam_"
  default_user_avatar_key: "default-user-avatar.webp"
  user_avatar_bucket_name: "user-avatar"
